package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "dondesang")
public class Adresse implements java.io.Serializable {

	private int idAdresse;
	private Ville ville;
	private Transport transport;
	private String rue;
	private String numero;
	private Set<Donneur> donneurs = new HashSet<Donneur>(0);

	public Adresse() {
	}

	public Adresse(int idAdresse, Ville ville, Transport transport, String rue,
			String numero) {
		this.idAdresse = idAdresse;
		this.ville = ville;
		this.transport = transport;
		this.rue = rue;
		this.numero = numero;
	}

	public Adresse(int idAdresse, Ville ville, Transport transport, String rue,
			String numero, Set<Donneur> donneurs) {
		this.idAdresse = idAdresse;
		this.ville = ville;
		this.transport = transport;
		this.rue = rue;
		this.numero = numero;
		this.donneurs = donneurs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idAdresse", unique = true, nullable = false)
	public int getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(int idAdresse) {
		this.idAdresse = idAdresse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVille", nullable = false)
	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTransport", nullable = true)
	public Transport getTransport() {
		return this.transport;
	}

	public void setTransport(Transport transport) {
		this.transport = transport;
	}

	@Column(name = "Rue", nullable = false, length = 100)
	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	@Column(name = "Numero", nullable = false, length = 5)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Donneur> getDonneurs() {
		return this.donneurs;
	}

	public void setDonneurs(Set<Donneur> donneurs) {
		this.donneurs = donneurs;
	}

}
