package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Analyse generated by hbm2java
 */
@Entity
@Table(name = "analyse", catalog = "dondesang")
public class Analyse implements java.io.Serializable {

	private int idAnalyse;
	private Detailsanalyse detailsanalyse;
	private Groupesanguin groupesanguin;
	private Set<Poche> poches = new HashSet<Poche>(0);

	public Analyse() {
	}

	public Analyse(int idAnalyse, Detailsanalyse detailsanalyse,
			Groupesanguin groupesanguin) {
		this.idAnalyse = idAnalyse;
		this.detailsanalyse = detailsanalyse;
		this.groupesanguin = groupesanguin;
	}

	public Analyse(int idAnalyse, Detailsanalyse detailsanalyse,
			Groupesanguin groupesanguin, Set<Poche> poches) {
		this.idAnalyse = idAnalyse;
		this.detailsanalyse = detailsanalyse;
		this.groupesanguin = groupesanguin;
		this.poches = poches;
	}

	@Id
	@Column(name = "idAnalyse", unique = true, nullable = false)
	public int getIdAnalyse() {
		return this.idAnalyse;
	}

	public void setIdAnalyse(int idAnalyse) {
		this.idAnalyse = idAnalyse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Det", nullable = false)
	public Detailsanalyse getDetailsanalyse() {
		return this.detailsanalyse;
	}

	public void setDetailsanalyse(Detailsanalyse detailsanalyse) {
		this.detailsanalyse = detailsanalyse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGrp", nullable = false)
	public Groupesanguin getGroupesanguin() {
		return this.groupesanguin;
	}

	public void setGroupesanguin(Groupesanguin groupesanguin) {
		this.groupesanguin = groupesanguin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "analyse")
	public Set<Poche> getPoches() {
		return this.poches;
	}

	public void setPoches(Set<Poche> poches) {
		this.poches = poches;
	}

}
