package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Collation generated by hbm2java
 */
@Entity
@Table(name = "collation", catalog = "dondesang")
public class Collation implements java.io.Serializable {

	private int idCollecte;
	private Collecte collecte;

	public Collation() {
	}

	public Collation(Collecte collecte) {
		this.collecte = collecte;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "collecte"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idCollecte", unique = true, nullable = false)
	public int getIdCollecte() {
		return this.idCollecte;
	}

	public void setIdCollecte(int idCollecte) {
		this.idCollecte = idCollecte;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Collecte getCollecte() {
		return this.collecte;
	}

	public void setCollecte(Collecte collecte) {
		this.collecte = collecte;
	}

}
