package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Collecte generated by hbm2java
 */
@Entity
@Table(name = "collecte", catalog = "dondesang", uniqueConstraints = @UniqueConstraint(columnNames = "idPoche"))
public class Collecte implements java.io.Serializable {

	private int idCollecte;
	private Medecin medecin;
	private Infirmiere infirmiere;
	private Stock stock;
	private Poche poche;
	private Date dateCollecte;
	private String typeCollecte;
	private Collation collation;

	public Collecte() {
	}

	public Collecte(int idCollecte, Medecin medecin, Infirmiere infirmiere,
			Stock stock, Poche poche, Date dateCollecte, String typeCollecte) {
		this.idCollecte = idCollecte;
		this.medecin = medecin;
		this.infirmiere = infirmiere;
		this.stock = stock;
		this.poche = poche;
		this.dateCollecte = dateCollecte;
		this.typeCollecte = typeCollecte;
	}

	public Collecte(int idCollecte, Medecin medecin, Infirmiere infirmiere,
			Stock stock, Poche poche, Date dateCollecte, String typeCollecte,
			Collation collation) {
		this.idCollecte = idCollecte;
		this.medecin = medecin;
		this.infirmiere = infirmiere;
		this.stock = stock;
		this.poche = poche;
		this.dateCollecte = dateCollecte;
		this.typeCollecte = typeCollecte;
		this.collation = collation;
	}

	@Id
	@Column(name = "idCollecte", unique = true, nullable = false)
	public int getIdCollecte() {
		return this.idCollecte;
	}

	public void setIdCollecte(int idCollecte) {
		this.idCollecte = idCollecte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMedecin", nullable = false)
	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idInfirmiere", nullable = false)
	public Infirmiere getInfirmiere() {
		return this.infirmiere;
	}

	public void setInfirmiere(Infirmiere infirmiere) {
		this.infirmiere = infirmiere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Sto", nullable = false)
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPoche", unique = true, nullable = false)
	public Poche getPoche() {
		return this.poche;
	}

	public void setPoche(Poche poche) {
		this.poche = poche;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateCollecte", nullable = false, length = 10)
	public Date getDateCollecte() {
		return this.dateCollecte;
	}

	public void setDateCollecte(Date dateCollecte) {
		this.dateCollecte = dateCollecte;
	}

	@Column(name = "TypeCollecte", nullable = false, length = 30)
	public String getTypeCollecte() {
		return this.typeCollecte;
	}

	public void setTypeCollecte(String typeCollecte) {
		this.typeCollecte = typeCollecte;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "collecte")
	public Collation getCollation() {
		return this.collation;
	}

	public void setCollation(Collation collation) {
		this.collation = collation;
	}

}
