package pojo;

// Generated 28 mai 2014 11:55:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conducteur generated by hbm2java
 */
@Entity
@Table(name = "conducteur", catalog = "dondesang")
public class Conducteur implements java.io.Serializable {

	private int idConducteur;
	private String nom;
	private String prenom;
	private String entreprisePrestataire;
	private Set<Transport> transports = new HashSet<Transport>(0);

	public Conducteur() {
	}

	public Conducteur(int idConducteur, String nom, String prenom,
			String entreprisePrestataire) {
		this.idConducteur = idConducteur;
		this.nom = nom;
		this.prenom = prenom;
		this.entreprisePrestataire = entreprisePrestataire;
	}

	public Conducteur(int idConducteur, String nom, String prenom,
			String entreprisePrestataire, Set<Transport> transports) {
		this.idConducteur = idConducteur;
		this.nom = nom;
		this.prenom = prenom;
		this.entreprisePrestataire = entreprisePrestataire;
		this.transports = transports;
	}

	@Id
	@Column(name = "idConducteur", unique = true, nullable = false)
	public int getIdConducteur() {
		return this.idConducteur;
	}

	public void setIdConducteur(int idConducteur) {
		this.idConducteur = idConducteur;
	}

	@Column(name = "Nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "EntreprisePrestataire", nullable = false, length = 50)
	public String getEntreprisePrestataire() {
		return this.entreprisePrestataire;
	}

	public void setEntreprisePrestataire(String entreprisePrestataire) {
		this.entreprisePrestataire = entreprisePrestataire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conducteur")
	public Set<Transport> getTransports() {
		return this.transports;
	}

	public void setTransports(Set<Transport> transports) {
		this.transports = transports;
	}

}
