package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Detailsanalyse generated by hbm2java
 */
@Entity
@Table(name = "detailsanalyse", catalog = "dondesang")
public class Detailsanalyse implements java.io.Serializable {

	private int idDet;
	private int hemoglobine;
	private int hematocrite;
	private int erythrocyte;
	private int leucocyte;
	private int lymphocyte;
	private int plaquette;
	private int fer;
	private int sodium;
	private int potassium;
	private int calcium;
	private Set<Analyse> analyses = new HashSet<Analyse>(0);

	public Detailsanalyse() {
	}

	public Detailsanalyse(int idDet, int hemoglobine, int hematocrite,
			int erythrocyte, int leucocyte, int lymphocyte, int plaquette,
			int fer, int sodium, int potassium, int calcium) {
		this.idDet = idDet;
		this.hemoglobine = hemoglobine;
		this.hematocrite = hematocrite;
		this.erythrocyte = erythrocyte;
		this.leucocyte = leucocyte;
		this.lymphocyte = lymphocyte;
		this.plaquette = plaquette;
		this.fer = fer;
		this.sodium = sodium;
		this.potassium = potassium;
		this.calcium = calcium;
	}

	public Detailsanalyse(int idDet, int hemoglobine, int hematocrite,
			int erythrocyte, int leucocyte, int lymphocyte, int plaquette,
			int fer, int sodium, int potassium, int calcium,
			Set<Analyse> analyses) {
		this.idDet = idDet;
		this.hemoglobine = hemoglobine;
		this.hematocrite = hematocrite;
		this.erythrocyte = erythrocyte;
		this.leucocyte = leucocyte;
		this.lymphocyte = lymphocyte;
		this.plaquette = plaquette;
		this.fer = fer;
		this.sodium = sodium;
		this.potassium = potassium;
		this.calcium = calcium;
		this.analyses = analyses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID_Det", unique = true, nullable = false)
	public int getIdDet() {
		return this.idDet;
	}

	public void setIdDet(int idDet) {
		this.idDet = idDet;
	}

	@Column(name = "Hemoglobine", nullable = false)
	public int getHemoglobine() {
		return this.hemoglobine;
	}

	public void setHemoglobine(int hemoglobine) {
		this.hemoglobine = hemoglobine;
	}

	@Column(name = "Hematocrite", nullable = false)
	public int getHematocrite() {
		return this.hematocrite;
	}

	public void setHematocrite(int hematocrite) {
		this.hematocrite = hematocrite;
	}

	@Column(name = "Erythrocyte", nullable = false)
	public int getErythrocyte() {
		return this.erythrocyte;
	}

	public void setErythrocyte(int erythrocyte) {
		this.erythrocyte = erythrocyte;
	}

	@Column(name = "Leucocyte", nullable = false)
	public int getLeucocyte() {
		return this.leucocyte;
	}

	public void setLeucocyte(int leucocyte) {
		this.leucocyte = leucocyte;
	}

	@Column(name = "Lymphocyte", nullable = false)
	public int getLymphocyte() {
		return this.lymphocyte;
	}

	public void setLymphocyte(int lymphocyte) {
		this.lymphocyte = lymphocyte;
	}

	@Column(name = "Plaquette", nullable = false)
	public int getPlaquette() {
		return this.plaquette;
	}

	public void setPlaquette(int plaquette) {
		this.plaquette = plaquette;
	}

	@Column(name = "Fer", nullable = false)
	public int getFer() {
		return this.fer;
	}

	public void setFer(int fer) {
		this.fer = fer;
	}

	@Column(name = "Sodium", nullable = false)
	public int getSodium() {
		return this.sodium;
	}

	public void setSodium(int sodium) {
		this.sodium = sodium;
	}

	@Column(name = "Potassium", nullable = false)
	public int getPotassium() {
		return this.potassium;
	}

	public void setPotassium(int potassium) {
		this.potassium = potassium;
	}

	@Column(name = "Calcium", nullable = false)
	public int getCalcium() {
		return this.calcium;
	}

	public void setCalcium(int calcium) {
		this.calcium = calcium;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detailsanalyse")
	public Set<Analyse> getAnalyses() {
		return this.analyses;
	}

	public void setAnalyses(Set<Analyse> analyses) {
		this.analyses = analyses;
	}

}
