package pojo;

// Generated 28 mai 2014 11:55:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Donneur generated by hbm2java
 */
@Entity
@Table(name = "donneur", catalog = "dondesang")
public class Donneur implements java.io.Serializable {

	private int idDonneur;
	private Groupesanguin groupesanguin;
	private Adresse adresse;
	private String nom;
	private String prenom;
	private int age;
	private char sexe;
	private Set<Formulaire> formulaires = new HashSet<Formulaire>(0);
	private Set<Poche> poches = new HashSet<Poche>(0);

	public Donneur() {
	}

	public Donneur(int idDonneur, Groupesanguin groupesanguin, Adresse adresse,
			String nom, String prenom, int age, char sexe) {
		this.idDonneur = idDonneur;
		this.groupesanguin = groupesanguin;
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.age = age;
		this.sexe = sexe;
	}

	public Donneur(int idDonneur, Groupesanguin groupesanguin, Adresse adresse,
			String nom, String prenom, int age, char sexe,
			Set<Formulaire> formulaires, Set<Poche> poches) {
		this.idDonneur = idDonneur;
		this.groupesanguin = groupesanguin;
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.age = age;
		this.sexe = sexe;
		this.formulaires = formulaires;
		this.poches = poches;
	}

	@Id
	@Column(name = "idDonneur", unique = true, nullable = false)
	public int getIdDonneur() {
		return this.idDonneur;
	}

	public void setIdDonneur(int idDonneur) {
		this.idDonneur = idDonneur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGrp", nullable = false)
	public Groupesanguin getGroupesanguin() {
		return this.groupesanguin;
	}

	public void setGroupesanguin(Groupesanguin groupesanguin) {
		this.groupesanguin = groupesanguin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAdresse", nullable = false)
	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	@Column(name = "Nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "Sexe", nullable = false, length = 1)
	public char getSexe() {
		return this.sexe;
	}

	public void setSexe(char sexe) {
		this.sexe = sexe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donneur")
	public Set<Formulaire> getFormulaires() {
		return this.formulaires;
	}

	public void setFormulaires(Set<Formulaire> formulaires) {
		this.formulaires = formulaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donneur")
	public Set<Poche> getPoches() {
		return this.poches;
	}

	public void setPoches(Set<Poche> poches) {
		this.poches = poches;
	}

}
