package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donneur generated by hbm2java
 */
@Entity
@Table(name = "donneur", catalog = "dondesang")
public class Donneur implements java.io.Serializable {

	private int idDonneur;
	private Groupesanguin groupesanguin;
	private Adresse adresse;
	private String nom;
	private String prenom;
	private Date dateNaissance;
	private char sexe;
	private String email;
	private String tel;
	private String gsm;
	private Set<Formulaire> formulaires = new HashSet<Formulaire>(0);
	private Set<Poche> poches = new HashSet<Poche>(0);

	public Donneur() {
	}

	public Donneur(int idDonneur, Groupesanguin groupesanguin, Adresse adresse,
			String nom, String prenom, Date dateNaissance, char sexe) {
		this.idDonneur = idDonneur;
		this.groupesanguin = groupesanguin;
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.sexe = sexe;
	}

	public Donneur(int idDonneur, Groupesanguin groupesanguin, Adresse adresse,
			String nom, String prenom, Date dateNaissance, char sexe,
			String email, String tel, String gsm, Set<Formulaire> formulaires,
			Set<Poche> poches) {
		this.idDonneur = idDonneur;
		this.groupesanguin = groupesanguin;
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.sexe = sexe;
		this.email = email;
		this.tel = tel;
		this.gsm = gsm;
		this.formulaires = formulaires;
		this.poches = poches;
	}

	@Id
	@Column(name = "idDonneur", unique = true, nullable = false)
	public int getIdDonneur() {
		return this.idDonneur;
	}

	public void setIdDonneur(int idDonneur) {
		this.idDonneur = idDonneur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGrp", nullable = false)
	public Groupesanguin getGroupesanguin() {
		return this.groupesanguin;
	}

	public void setGroupesanguin(Groupesanguin groupesanguin) {
		this.groupesanguin = groupesanguin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAdresse", nullable = false)
	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	@Column(name = "Nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateNaissance", nullable = false, length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "Sexe", nullable = false, length = 1)
	public char getSexe() {
		return this.sexe;
	}

	public void setSexe(char sexe) {
		this.sexe = sexe;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "tel", length = 30)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "gsm", length = 30)
	public String getGsm() {
		return this.gsm;
	}

	public void setGsm(String gsm) {
		this.gsm = gsm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donneur")
	public Set<Formulaire> getFormulaires() {
		return this.formulaires;
	}

	public void setFormulaires(Set<Formulaire> formulaires) {
		this.formulaires = formulaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donneur")
	public Set<Poche> getPoches() {
		return this.poches;
	}

	public void setPoches(Set<Poche> poches) {
		this.poches = poches;
	}

}
