package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Formulaire generated by hbm2java
 */
@Entity
@Table(name = "formulaire", catalog = "dondesang")
public class Formulaire implements java.io.Serializable {

	private int idFormulaire;
	private Donneur donneur;
	private String tatouage;
	private String piercing;
	private String operation;
	private String maladieRecente;

	public Formulaire() {
	}

	public Formulaire(int idFormulaire, Donneur donneur, String tatouage,
			String piercing, String operation, String maladieRecente) {
		this.idFormulaire = idFormulaire;
		this.donneur = donneur;
		this.tatouage = tatouage;
		this.piercing = piercing;
		this.operation = operation;
		this.maladieRecente = maladieRecente;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idFormulaire", unique = true, nullable = false)
	public int getIdFormulaire() {
		return this.idFormulaire;
	}

	public void setIdFormulaire(int idFormulaire) {
		this.idFormulaire = idFormulaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDonneur", nullable = false)
	public Donneur getDonneur() {
		return this.donneur;
	}

	public void setDonneur(Donneur donneur) {
		this.donneur = donneur;
	}

	@Column(name = "tatouage", nullable = false, length = 250)
	public String getTatouage() {
		return this.tatouage;
	}

	public void setTatouage(String tatouage) {
		this.tatouage = tatouage;
	}

	@Column(name = "piercing", nullable = false, length = 250)
	public String getPiercing() {
		return this.piercing;
	}

	public void setPiercing(String piercing) {
		this.piercing = piercing;
	}

	@Column(name = "operation", nullable = false, length = 250)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "MaladieRecente", nullable = false, length = 250)
	public String getMaladieRecente() {
		return this.maladieRecente;
	}

	public void setMaladieRecente(String maladieRecente) {
		this.maladieRecente = maladieRecente;
	}

}
