package pojo;

// Generated 3 juin 2014 10:48:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Formulaire generated by hbm2java
 */
@Entity
@Table(name = "formulaire", catalog = "dondesang")
public class Formulaire implements java.io.Serializable {

	private Integer idFormulaire;
	private Donneur donneur;
	private byte[] file;

	public Formulaire() {
	}

	public Formulaire(Donneur donneur, byte[] file) {
		this.donneur = donneur;
		this.file = file;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFormulaire", unique = true, nullable = false)
	public Integer getIdFormulaire() {
		return this.idFormulaire;
	}

	public void setIdFormulaire(Integer idFormulaire) {
		this.idFormulaire = idFormulaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDonneur", nullable = false)
	public Donneur getDonneur() {
		return this.donneur;
	}

	public void setDonneur(Donneur donneur) {
		this.donneur = donneur;
	}

	@Column(name = "File", nullable = false)
	public byte[] getFile() {
		return this.file;
	}

	public void setFile(byte[] file) {
		this.file = file;
	}

}
