package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupesanguin generated by hbm2java
 */
@Entity
@Table(name = "groupesanguin", catalog = "dondesang")
public class Groupesanguin implements java.io.Serializable {

	private int idGrp;
	private String grp;
	private char rhesus;
	private Set<Analyse> analyses = new HashSet<Analyse>(0);
	private Set<Donneur> donneurs = new HashSet<Donneur>(0);

	public Groupesanguin() {
	}

	public Groupesanguin(int idGrp, String grp, char rhesus) {
		this.idGrp = idGrp;
		this.grp = grp;
		this.rhesus = rhesus;
	}

	public Groupesanguin(int idGrp, String grp, char rhesus,
			Set<Analyse> analyses, Set<Donneur> donneurs) {
		this.idGrp = idGrp;
		this.grp = grp;
		this.rhesus = rhesus;
		this.analyses = analyses;
		this.donneurs = donneurs;
	}

	@Id
	@Column(name = "idGrp", unique = true, nullable = false)
	public int getIdGrp() {
		return this.idGrp;
	}

	public void setIdGrp(int idGrp) {
		this.idGrp = idGrp;
	}

	@Column(name = "Grp", nullable = false, length = 2)
	public String getGrp() {
		return this.grp;
	}

	public void setGrp(String grp) {
		this.grp = grp;
	}

	@Column(name = "Rhesus", nullable = false, length = 1)
	public char getRhesus() {
		return this.rhesus;
	}

	public void setRhesus(char rhesus) {
		this.rhesus = rhesus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupesanguin")
	public Set<Analyse> getAnalyses() {
		return this.analyses;
	}

	public void setAnalyses(Set<Analyse> analyses) {
		this.analyses = analyses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupesanguin")
	public Set<Donneur> getDonneurs() {
		return this.donneurs;
	}

	public void setDonneurs(Set<Donneur> donneurs) {
		this.donneurs = donneurs;
	}

}
