package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Poche generated by hbm2java
 */
@Entity
@Table(name = "poche", catalog = "dondesang", uniqueConstraints = @UniqueConstraint(columnNames = "idAnalyse"))
public class Poche implements java.io.Serializable {

	private int idPoche;
	private Analyse analyse;
	private Donneur donneur;
	private boolean autotransfusion;
	private boolean utilise;
	private boolean etat;
	private Set<Collecte> collectes = new HashSet<Collecte>(0);

	public Poche() {
	}

	public Poche(int idPoche, Analyse analyse, Donneur donneur,
			boolean autotransfusion, boolean utilise, boolean etat) {
		this.idPoche = idPoche;
		this.analyse = analyse;
		this.donneur = donneur;
		this.autotransfusion = autotransfusion;
		this.utilise = utilise;
		this.etat = etat;
	}

	public Poche(int idPoche, Analyse analyse, Donneur donneur,
			boolean autotransfusion, boolean utilise, boolean etat,
			Set<Collecte> collectes) {
		this.idPoche = idPoche;
		this.analyse = analyse;
		this.donneur = donneur;
		this.autotransfusion = autotransfusion;
		this.utilise = utilise;
		this.etat = etat;
		this.collectes = collectes;
	}

	@Id
	@Column(name = "idPoche", unique = true, nullable = false)
	public int getIdPoche() {
		return this.idPoche;
	}

	public void setIdPoche(int idPoche) {
		this.idPoche = idPoche;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAnalyse", unique = true, nullable = false)
	public Analyse getAnalyse() {
		return this.analyse;
	}

	public void setAnalyse(Analyse analyse) {
		this.analyse = analyse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDonneur", nullable = false)
	public Donneur getDonneur() {
		return this.donneur;
	}

	public void setDonneur(Donneur donneur) {
		this.donneur = donneur;
	}

	@Column(name = "autotransfusion", nullable = false)
	public boolean isAutotransfusion() {
		return this.autotransfusion;
	}

	public void setAutotransfusion(boolean autotransfusion) {
		this.autotransfusion = autotransfusion;
	}

	@Column(name = "utilise", nullable = false)
	public boolean isUtilise() {
		return this.utilise;
	}

	public void setUtilise(boolean utilise) {
		this.utilise = utilise;
	}

	@Column(name = "etat", nullable = false)
	public boolean isEtat() {
		return this.etat;
	}

	public void setEtat(boolean etat) {
		this.etat = etat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poche")
	public Set<Collecte> getCollectes() {
		return this.collectes;
	}

	public void setCollectes(Set<Collecte> collectes) {
		this.collectes = collectes;
	}

}
