package pojo;

// Generated 30 mai 2014 10:49:31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", catalog = "dondesang")
public class Stock implements java.io.Serializable {

	private int idSto;
	private Set<Collecte> collectes = new HashSet<Collecte>(0);
	private Set<Transport> transports = new HashSet<Transport>(0);

	public Stock() {
	}

	public Stock(int idSto) {
		this.idSto = idSto;
	}

	public Stock(int idSto, Set<Collecte> collectes, Set<Transport> transports) {
		this.idSto = idSto;
		this.collectes = collectes;
		this.transports = transports;
	}

	@Id
	@Column(name = "ID_Sto", unique = true, nullable = false)
	public int getIdSto() {
		return this.idSto;
	}

	public void setIdSto(int idSto) {
		this.idSto = idSto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stock")
	public Set<Collecte> getCollectes() {
		return this.collectes;
	}

	public void setCollectes(Set<Collecte> collectes) {
		this.collectes = collectes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stock")
	public Set<Transport> getTransports() {
		return this.transports;
	}

	public void setTransports(Set<Transport> transports) {
		this.transports = transports;
	}

}
