package pojo;

// Generated 28 mai 2014 11:55:57 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transport generated by hbm2java
 */
@Entity
@Table(name = "transport", catalog = "dondesang")
public class Transport implements java.io.Serializable {

	private int idTransport;
	private Conducteur conducteur;
	private Stock stock;
	private Date dateTransport;
	private Date heureReception;
	private Set<Adresse> adresses = new HashSet<Adresse>(0);

	public Transport() {
	}

	public Transport(int idTransport, Conducteur conducteur, Stock stock,
			Date dateTransport, Date heureReception) {
		this.idTransport = idTransport;
		this.conducteur = conducteur;
		this.stock = stock;
		this.dateTransport = dateTransport;
		this.heureReception = heureReception;
	}

	public Transport(int idTransport, Conducteur conducteur, Stock stock,
			Date dateTransport, Date heureReception, Set<Adresse> adresses) {
		this.idTransport = idTransport;
		this.conducteur = conducteur;
		this.stock = stock;
		this.dateTransport = dateTransport;
		this.heureReception = heureReception;
		this.adresses = adresses;
	}

	@Id
	@Column(name = "idTransport", unique = true, nullable = false)
	public int getIdTransport() {
		return this.idTransport;
	}

	public void setIdTransport(int idTransport) {
		this.idTransport = idTransport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idConducteur", nullable = false)
	public Conducteur getConducteur() {
		return this.conducteur;
	}

	public void setConducteur(Conducteur conducteur) {
		this.conducteur = conducteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_Sto", nullable = false)
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateTransport", nullable = false, length = 10)
	public Date getDateTransport() {
		return this.dateTransport;
	}

	public void setDateTransport(Date dateTransport) {
		this.dateTransport = dateTransport;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "HeureReception", nullable = false, length = 10)
	public Date getHeureReception() {
		return this.heureReception;
	}

	public void setHeureReception(Date heureReception) {
		this.heureReception = heureReception;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transport")
	public Set<Adresse> getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Set<Adresse> adresses) {
		this.adresses = adresses;
	}

}
